kind : Service
apiVersion : v1
metadata :
  name : self-healing-service
spec: 
  type : NodePort
  selector : 
    app : self-healing
  ports :
    - port : 5000
      targetPort : 5000
      nodePort :  30008


